/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as VerificationPendingImport } from './routes/verification-pending'
import { Route as MainPageImport } from './routes/main-page'
import { Route as DonasiImport } from './routes/donasi'
import { Route as BuatObjekImport } from './routes/buat-objek'
import { Route as AboutUsImport } from './routes/about-us'
import { Route as IndexImport } from './routes/index'
import { Route as ObjekObjekImport } from './routes/objek_/$objek'

// Create/Update Routes

const VerificationPendingRoute = VerificationPendingImport.update({
  path: '/verification-pending',
  getParentRoute: () => rootRoute,
} as any)

const MainPageRoute = MainPageImport.update({
  path: '/main-page',
  getParentRoute: () => rootRoute,
} as any)

const DonasiRoute = DonasiImport.update({
  path: '/donasi',
  getParentRoute: () => rootRoute,
} as any)

const BuatObjekRoute = BuatObjekImport.update({
  path: '/buat-objek',
  getParentRoute: () => rootRoute,
} as any)

const AboutUsRoute = AboutUsImport.update({
  path: '/about-us',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ObjekObjekRoute = ObjekObjekImport.update({
  path: '/objek/$objek',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsImport
      parentRoute: typeof rootRoute
    }
    '/buat-objek': {
      id: '/buat-objek'
      path: '/buat-objek'
      fullPath: '/buat-objek'
      preLoaderRoute: typeof BuatObjekImport
      parentRoute: typeof rootRoute
    }
    '/donasi': {
      id: '/donasi'
      path: '/donasi'
      fullPath: '/donasi'
      preLoaderRoute: typeof DonasiImport
      parentRoute: typeof rootRoute
    }
    '/main-page': {
      id: '/main-page'
      path: '/main-page'
      fullPath: '/main-page'
      preLoaderRoute: typeof MainPageImport
      parentRoute: typeof rootRoute
    }
    '/verification-pending': {
      id: '/verification-pending'
      path: '/verification-pending'
      fullPath: '/verification-pending'
      preLoaderRoute: typeof VerificationPendingImport
      parentRoute: typeof rootRoute
    }
    '/objek/$objek': {
      id: '/objek/$objek'
      path: '/objek/$objek'
      fullPath: '/objek/$objek'
      preLoaderRoute: typeof ObjekObjekImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  AboutUsRoute,
  BuatObjekRoute,
  DonasiRoute,
  MainPageRoute,
  VerificationPendingRoute,
  ObjekObjekRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about-us",
        "/buat-objek",
        "/donasi",
        "/main-page",
        "/verification-pending",
        "/objek/$objek"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about-us": {
      "filePath": "about-us.tsx"
    },
    "/buat-objek": {
      "filePath": "buat-objek.tsx"
    },
    "/donasi": {
      "filePath": "donasi.tsx"
    },
    "/main-page": {
      "filePath": "main-page.tsx"
    },
    "/verification-pending": {
      "filePath": "verification-pending.tsx"
    },
    "/objek/$objek": {
      "filePath": "objek_/$objek.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
